Ruby/AnimalFinder/config/routes.rb
Rails.application.routes.draw do

	get '/' => 'animals#index'
	get '/animals/todos' => 'animals#todos'
	get '/animals/encontrei/:id' => 'animals#encontrei'

  resources :animals
  resources :donos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Ruby/AnimalFinder/app/models/animal.rb
class Animal < ApplicationRecord
end

Ruby/AnimalFinder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby/AnimalFinder/app/models/dono.rb
class Dono < ApplicationRecord
end

Ruby/AnimalFinder/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.where.not(status:"Comunicado").or(Animal.where.not(status:"Encontrado"))#Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  def encontrei
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:Nome, :Idade, :InformacoesExtras, :Cidade, :Estado, :Status, :IdDono, :EncontradoPor, :TelefoneContato, :Localizacao)
    end
end

Ruby/AnimalFinder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ruby/AnimalFinder/app/controllers/donos_controller.rb
class DonosController < ApplicationController
  before_action :set_dono, only: [:show, :edit, :update, :destroy]

  # GET /donos
  # GET /donos.json
  def index
    @donos = Dono.all
  end

  # GET /donos/1
  # GET /donos/1.json
  def show
  end

  # GET /donos/new
  def new
    @dono = Dono.new
  end

  # GET /donos/1/edit
  def edit
  end

  # POST /donos
  # POST /donos.json
  def create
    @dono = Dono.new(dono_params)

    respond_to do |format|
      if @dono.save
        format.html { redirect_to @dono, notice: 'Dono was successfully created.' }
        format.json { render :show, status: :created, location: @dono }
      else
        format.html { render :new }
        format.json { render json: @dono.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donos/1
  # PATCH/PUT /donos/1.json
  def update
    respond_to do |format|
      if @dono.update(dono_params)
        format.html { redirect_to @dono, notice: 'Dono was successfully updated.' }
        format.json { render :show, status: :ok, location: @dono }
      else
        format.html { render :edit }
        format.json { render json: @dono.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donos/1
  # DELETE /donos/1.json
  def destroy
    @dono.destroy
    respond_to do |format|
      format.html { redirect_to donos_url, notice: 'Dono was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dono
      @dono = Dono.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dono_params
      params.require(:dono).permit(:Nome, :Email, :Telefone, :Senha)
    end
end

Ruby/AnimalFinder/app/helpers/animals_helper.rb
module AnimalsHelper
end

Ruby/AnimalFinder/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/AnimalFinder/app/helpers/donos_helper.rb
module DonosHelper
end

Ruby/AnimalFinder/app/views/donos/_form.html.erb
<%= form_with(model: dono, local: true) do |form| %>
  <% if dono.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dono.errors.count, "error") %> prohibited this dono from being saved:</h2>

      <ul>
      <% dono.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome, id: :dono_Nome %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email, id: :dono_Email %>
  </div>

  <div class="field">
    <%= form.label :Telefone %>
    <%= form.text_field :Telefone, id: :dono_Telefone %>
  </div>

  <div class="field">
    <%= form.label :Senha %>
    <%= form.text_field :Senha, id: :dono_Senha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Ruby/AnimalFinder/app/views/donos/edit.html.erb
<h1>Editing Dono</h1>

<%= render 'form', dono: @dono %>

<%= link_to 'Show', @dono %> |
<%= link_to 'Back', donos_path %>

Ruby/AnimalFinder/app/views/donos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donos.each do |dono| %>
      <tr>
        <td><%= dono.Nome %></td>
        <td><%= dono.Email %></td>
        <td><%= dono.Telefone %></td>
        <td><%= dono.Senha %></td>
        <td><%= link_to 'Show', dono %></td>
        <td><%= link_to 'Edit', edit_dono_path(dono) %></td>
        <td><%= link_to 'Destroy', dono, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dono', new_dono_path %>

Ruby/AnimalFinder/app/views/donos/new.html.erb
<h1>New Dono</h1>

<%= render 'form', dono: @dono %>

<%= link_to 'Back', donos_path %>

Ruby/AnimalFinder/app/views/donos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @dono.Nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dono.Email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @dono.Telefone %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @dono.Senha %>
</p>

<%= link_to 'Edit', edit_dono_path(@dono) %> |
<%= link_to 'Back', donos_path %>

Ruby/AnimalFinder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>